name: Simple test

on:
  # Triggers the workflow on push for staging branch
  push:
    branches:
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up home
        run: |
          echo "HOME=/home/ubuntu" >> ${GITHUB_ENV}
      - name: Install Rust
        if: ${{ !cancelled() }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run test suite with cargo
        run: cargo test
      - name: Sleep to test EC2 activity
        run: sleep 180
