# Start all benchmark jobs on Slab CI bot.
name: Start all benchmarks

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  start-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Start AWS job in Slab
        shell: bash
        run: |
          echo -n '{"command": "cpu_test", "git_ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' > command.json
          curl -v -k \
          -H "Content-Type: application/json" \
          -H "X-Slab-Repository: ${{ github.repository }}" \
          -H "X-Slab-Command: start_aws" \
          -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
          -d @command.json \
          ${{ secrets.SLAB_URL }}
